

# This file was *autogenerated* from the file draw_tetrahedron.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p8 = RealNumber('0.8'); _sage_const_1 = Integer(1)#!/usr/bin/env sage
from sage.all import *

T = tetrahedron(color='red', opacity=_sage_const_0p8 , mesh=True)

T.show(title="3D", frame=True, aspect_ratio=_sage_const_1 )

