

# This file was *autogenerated* from the file ./factor.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)#!/usr/bin/env sage

import sys
from sage.all import *

if len(sys.argv) != _sage_const_2 :
    print("Usage: %s <n>" % sys.argv[_sage_const_0 ])
    print("Outputs the prime factorization of n.")
    sys.exit(_sage_const_1 )

print(factor(sage_eval(sys.argv[_sage_const_1 ])))

