

# This file was *autogenerated* from the file realize.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
import sys

# Get sequence from command line arguments
try:
    # Integer() is a Sage-specific type that works in .sage files
    d_seq = [Integer(x) for x in sys.argv[_sage_const_1 :]]
except (ValueError, IndexError):
    print("Usage: sage realize.sage 3 3 2 2 2")
    sys.exit(_sage_const_1 )

if not d_seq:
    print("Error: No degree sequence provided.")
else:
    print(f"Testing sequence: {d_seq}")
    
    try:
        # graphs.DegreeSequence uses Havel-Hakimi by default to realize the graph
        # It will raise a ValueError if the sequence is not graphic
        G = graphs.DegreeSequence(d_seq)
        
        print("Sequence is graphic! Building graph...")
        
        # Save and show the plot
        output = "realization.png"
        P = G.plot(vertex_labels=True, title=f"Havel-Hakimi Realization: {d_seq}")
        P.save(output)
        
        print(f"Success! Realization saved to {output}")
        # Note: G.show() requires a GUI environment to open automatically
        G.show()

    except ValueError:
        print("Error: The sequence is NOT graphic (Handshaking lemma or Havel-Hakimi failed).")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

